P8105 Homework 1
================
Yikai Lu
2026-09-18

# Problem 1

``` r
#install.packages("palmerpenguins")
data("penguins", package = "palmerpenguins")
```

\#try to describe the data

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

\#from the result, we can see there is 344 rows and 8 columns for this
dataset

``` r
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

\#The dataset contains information about penguins, including species,
island, bill length, bill depth, flipper length, body mass, sex, and
year.

``` r
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

\#The mean flipper length is 200.92 mm.

``` r
#install.packages("ggplot2")
library(ggplot2)
```
